#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H

#include "hardware_hal.h"

#define ENABLE_TASK_SERIAL        1
#define ENABLE_TASK_BLINK         1
#define ENABLE_TASK_STEPPER_BASE      1
#define ENABLE_TASK_STEPPER_ARM       1
#define ENABLE_TASK_POT_BASE          1
#define ENABLE_TASK_POT_ARM           1
#define ENABLE_TASK_CONTROLLER_BASE   1
#define ENABLE_TASK_CONTROLLER_ARM    1

#define SERIAL_TASK_STACK_SIZE    4096
#define SERIAL_TASK_PRIORITY      3
#define SERIAL_LOG_QUEUE_LENGTH   16

#define BLINK_TASK_STACK_SIZE     2048
#define BLINK_TASK_PRIORITY       1

#define STEPPER_TASK_STACK_SIZE   4096
#define STEPPER_TASK_PRIORITY     2
#define STEPPER_QUEUE_LENGTH      8
#define STEPPER_COMPLETION_QUEUE  8

#define STEPPER_DEFAULT_RELEASE   true
#define STEPPER_DEFAULT_USE_RAMP  true

#define POT_TASK_STACK_SIZE            2048
#define POT_TASK_PRIORITY              1
#define POT_SAMPLE_DELAY_MS            50
#define POT_ECHO_MIN_INTERVAL_MS       1000
#define POT_ECHO_MIN_DELTA_PERCENT     1.0f
#define POT_SAMPLE_QUEUE_LENGTH        1

#define CONTROLLER_TASK_STACK_SIZE         4096
#define CONTROLLER_TASK_PRIORITY           2
#define CONTROLLER_DEADBAND_PERCENT        2.0f
#define CONTROLLER_PERCENT_TO_STEPS        10.0f
#define CONTROLLER_MAX_STEPS_PER_COMMAND   400
#define CONTROLLER_COMMAND_INTERVAL_MS     100
#define CONTROLLER_ECHO_INTERVAL_MS        1000
#define CONTROLLER_DEFAULT_SETPOINT        50.0f

#define SERIAL_COMMAND_PROMPT     "> "

#endif // SYSTEM_CONFIG_H
