#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H

#include "hardware_hal.h"

#define ENABLE_TASK_SERIAL        1
#define ENABLE_TASK_BLINK         1
#define ENABLE_TASK_STEPPER_BASE  1
#define ENABLE_TASK_STEPPER_ARM   1
#define ENABLE_TASK_POT_BASE      1
#define ENABLE_TASK_POT_ARM       1

#define SERIAL_TASK_STACK_SIZE    4096
#define SERIAL_TASK_PRIORITY      3
#define SERIAL_LOG_QUEUE_LENGTH   16

#define BLINK_TASK_STACK_SIZE     2048
#define BLINK_TASK_PRIORITY       1

#define STEPPER_TASK_STACK_SIZE   4096
#define STEPPER_TASK_PRIORITY     2
#define STEPPER_QUEUE_LENGTH      8
#define STEPPER_COMPLETION_QUEUE  8

#define STEPPER_DEFAULT_RELEASE   true
#define STEPPER_DEFAULT_USE_RAMP  true

#define POT_TASK_STACK_SIZE       2048
#define POT_TASK_PRIORITY         1
#define POT_SAMPLE_DELAY_MS       50

#define SERIAL_COMMAND_PROMPT     "> "

#endif // SYSTEM_CONFIG_H
